//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoanApplication
    {
        public int LoanId { get; set; }

        [Required(ErrorMessage ="PropertyLocation is Required")]
        public string PropertyLocation { get; set; }

        [Required(ErrorMessage = "PropertyName is Required")]
        public string PropertyName { get; set; }

        [Required(ErrorMessage = "Estimatedcostofproperty is Required")]
        public decimal EstimatedCostOfProperty { get; set; }

        [Required(ErrorMessage = "Amount is Required")]
        public decimal AmountRequired { get; set; }

        [Required(ErrorMessage = "Monthly income is Required")]
        public decimal MonthlyIncome { get; set; }

        [Required(ErrorMessage = "Name is Required")]
        public string Name { get; set; }

        [Range(22,60,ErrorMessage ="Min Age is 22 and Max age is 60")]
        public int Age { get; set; }
        [Required(ErrorMessage = "Date Of Birth is Required")]
        [Display(Name = "Date Of Birth")]
       // [DisplayFormat(DataFormatString = "{0:dd-mm-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DateOfBirth { get; set; }

        //[Display(Name = "AadharNumber:")]
        //[Required(ErrorMessage = "AadharNumber is Required")]
        //[RegularExpression("^[2-9]{1}[0-9]{3}\\s[0 - 9]{ 4}\\s[0 - 9]{4}$", ErrorMessage = "Invalid Aadhar Number")]
        public decimal AadharNumber { get; set; }

        //[Display(Name = "Pan Number:")]
        //[Required(ErrorMessage = "Pan Number is Required")]
        //[RegularExpression("^([A-Za-z]){5} ([0-9]) {4} ([A-Za-z]) {1}$", ErrorMessage = "Invalid Pan Number")]
        public string PanNumber { get; set; }
        public bool Verified { get; set; }
        public bool Approved { get; set; }
    }
}
